name: CI Check
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: NPM Install
        run: npm install
      - name: Check Format
        run: npm run format:check
      - name: Run Linter
        run: npm run lint
